AutoBouquetsMaker/src/scanner/dvbscanner.py

When multiple NIT-other tables (for multiple network IDs) are being published in the transport stream, try to process all of them rather than the previous behaviour of processing only the first one seen.
Every NIT-other table received will be processed until one of the following conditions is true:
- A NIT-other section is received with a network ID and version number matching one we've already processed, and all NIT-other tables we've seen are complete (we've received and processed all the sections)
- TIMEOUT_SEC has elapsed
Not having a definitive way to know how many different NIT-other tables are being published, this assumes that the NIT-other tables are transmitted as a repeating loop with network IDs in the same order each time. This matches the observed behaviour of every …

Process multiple NIT-other tables

---

AutoBouquetsMaker/po/es.po

Add spanish translations

---

AutoBouquetsMaker/po/sv.po

Made a Swedish translation for ABM.

Uploaded Swedish translation

---

AutoBouquetsMaker/po/el.po

ABM Greek translation update 15/2/2018

ABM Greek translation update 15/2/2018

---

AutoBouquetsMaker/providers/cable_uk_virgin.xml

This seemed to have moved encryption since the first event.

Blacklist ITV PPV HD

---

AutoBouquetsMaker/providers/cable_ie_mk2.xml

added MTV Love to fta_corrections

MTV Love added to fta_corrections

---

AutoBouquetsMaker/providers/cable_nl.xml

* Addded missing provider entry's to the cables_nl.xml.
etc...

Updated cable_nl.xml

---

AutoBouquetsMaker/providers/cable_uk_virgin.xml

[DVB-C UK] Update tuning details for 40981, 00002.

---

AutoBouquetsMaker/po/pt.po

[translations] AutoBouquetsMaker portuguese translation - update

---

AutoBouquetsMaker/po/it.po

Added several lines and reviewed previous ones.

translation] AutoBouquetsMaker italian language translation - update

---

AutoBouquetsMaker/providers/cable_uk_virgin.xml

remove either no longer broadcasting or 1850 caid dead channels that do not clear.

remove more dead channels

---

.travis.yml
AutoBouquetsMaker/lib/dvbreader.c
AutoBouquetsMaker/src/about.py
AutoBouquetsMaker/src/deletebouquets.py
AutoBouquetsMaker/src/hidesections.py
AutoBouquetsMaker/src/keepbouquets.py
AutoBouquetsMaker/src/log.py
AutoBouquetsMaker/src/menu.py
AutoBouquetsMaker/src/ordering.py
AutoBouquetsMaker/src/plugin.py
AutoBouquetsMaker/src/scanner/bouquetsreader.py
AutoBouquetsMaker/src/scanner/bouquetswriter.py
AutoBouquetsMaker/src/scanner/dvbscanner.py
AutoBouquetsMaker/src/scanner/frequencyfinder.py
AutoBouquetsMaker/src/scanner/main.py
AutoBouquetsMaker/src/scanner/manager.py
AutoBouquetsMaker/src/scanner/providers.py
AutoBouquetsMaker/src/scanner/tools.py
AutoBouquetsMaker/src/setup.py
AutoBouquetsMaker/src/updateproviders.py
xml2po.py

uses six.ensure only with builds for python3 (assumes >= six-1.12.0)
remain compatible with builds using python2 (assumes < six-1.12.0)

[2to3] add python3 support

---

.travis.yml

remove obsolete p3check branch testing

[.travis.yml] update branches

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

Dave ja vu

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[Sky 28.2] HD swap for TJC HD

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

Sky Arts HD swap (new channel numbers)

Sky Arts HD swap

---

AutoBouquetsMaker/providers/sat_450_vivacom.xml

Update Vivacom Reference TP on 45.0°E
morph

45.0°E - Vivacom Update

---

AutoBouquetsMaker/providers/sat_282_sky_uk.xml

For BBC Three on Sky UK.
I don't know the numbers for Sky Ireland yet.

Update sat_282_sky_uk.xml with HD swaps for BBC Three

---

AutoBouquetsMaker/providers/terrestrial_uk_freeview.xml

Fixed COM7 mux frequency for Rowridge
Added service hacks for Rowridge, to stop the incorrect NIT being parsed

[terrestrial] Fixes for Rowridge

---

AutoBouquetsMaker/lib/dvbreader.c
AutoBouquetsMaker/src/scanner/dvbscanner.py

@AbuBaniaz as you requested separated push

Support for LCN descriptor_tag 0x82

---

AutoBouquetsMaker/src/setup.py

Fix the providers list region sort with accents.

Fix region sort with accents

---

AutoBouquetsMaker/providers/terrestrial_pt_tdt.xml

With https://github.com/oe-alliance/AutoBouquetsMaker/pull/244 customtransponders not needed for pt_tdt

customtransponders not needed for pt_tdt

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

This reverts commit 8339fac1d8d346d3a2a58a5130653f9b07abc622.

Revert "[Sky 28.2] MTA1 World HD swap (#251)"

---

AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[28.2E] BBC ALBA HD Swap.
UK only, BBC ALBA is not on Sky Ireland.

[28.2E] BBC ALBA HD Swap.

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[28.2E] BBC Parliament HD swap

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[28.2E] BBC Three HD swap

---

AutoBouquetsMaker/src/scanner/bouquetswriter.py

This patch will make section_sep not needed and simplify the code.
@Huevos

[bouquetswriter] make section_sep not needed

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[Sky 28.2] Do not show adult services when Adult section is hidden

---

xml2po.py

indentation contains mixed spaces and tabs

PEP8 E101 - silence warnings

---

AutoBouquetsMaker/src/menu.py
AutoBouquetsMaker/src/plugin.py
AutoBouquetsMaker/src/scanner/__init__.py
AutoBouquetsMaker/src/scanner/bouquetsreader.py
AutoBouquetsMaker/src/scanner/bouquetswriter.py
AutoBouquetsMaker/src/scanner/dvbscanner.py
AutoBouquetsMaker/src/scanner/freesat_regions_extractor.py
AutoBouquetsMaker/src/scanner/frequencyfinder.py
AutoBouquetsMaker/src/scanner/main.py
AutoBouquetsMaker/src/scanner/manager.py
AutoBouquetsMaker/src/scanner/providerconfig.py
AutoBouquetsMaker/src/scanner/providers.py
AutoBouquetsMaker/src/scanner/tools.py
AutoBouquetsMaker/src/setup.py
AutoBouquetsMaker/src/skin_templates.py
AutoBouquetsMaker/src/updateproviders.py

whitespace added/removed to silence 247 comment warnings
E261 at least two spaces before inline comment
E265 block comment should start with '# '

PEP8 E261,E265 - silence warnings

---

.github/workflows/autobouquetsmaker.yml
AutoBouquetsMaker/src/hidesections.py
AutoBouquetsMaker/src/keepbouquets.py
AutoBouquetsMaker/src/scanner/bouquetswriter.py
AutoBouquetsMaker/src/scanner/manager.py
AutoBouquetsMaker/src/scanner/providers.py
AutoBouquetsMaker/src/scanner/tools.py
AutoBouquetsMaker/src/setup.py
AutoBouquetsMaker/src/updateproviders.py

silence last of the remaining whitespace warnings in the workflow flake8 linter.

PEP8 - silence warnings

---

AutoBouquetsMaker/src/plugin.py

Fixed localisation of  descriptions.

Updated plugin.py

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

[28.2E] London Live became London TV
