AutoBouquetsMaker/custom/README.txt
AutoBouquetsMaker/providers/sat_130_bistv.xml

This provides a bouquet for the French subscription service Bis TV on Hot Bird at 13°E. A slightly different version of the package is also provided on Eutelsat 5 West A.

Add Bis TV on Hot Bird

---

AutoBouquetsMaker/providers/sat_192_tntsat.xml

- Update transponder settings to reflect recent satellite change
- Disable nit_other_table scanning to improve speed
- Capitalize and space bouquet name correctly to match official branding

Update TNT SAT bouquet

---

AutoBouquetsMaker/providers/sat_192_canalsat.xml

- Update transponder settings to reflect recent satellite change
- Disable nit_other_table scanning to improve speed

Update CanalSat France bouquet

---

AutoBouquetsMaker/custom/hd_sat_0192_hd+_CustomLCN.xml
AutoBouquetsMaker/providers/sat_0192_hd+.xml
AutoBouquetsMaker/providers/sat_0192_hd+10.xml
AutoBouquetsMaker/providers/sat_0192_hd+11.xml
AutoBouquetsMaker/providers/sat_0192_hd+12.xml
AutoBouquetsMaker/providers/sat_0192_hd+13.xml
AutoBouquetsMaker/providers/sat_0192_hd+14.xml
AutoBouquetsMaker/providers/sat_0192_hd+15.xml
AutoBouquetsMaker/providers/sat_0192_hd+2.xml
AutoBouquetsMaker/providers/sat_0192_hd+3.xml
AutoBouquetsMaker/providers/sat_0192_hd+4.xml
AutoBouquetsMaker/providers/sat_0192_hd+5.xml
AutoBouquetsMaker/providers/sat_0192_hd+6.xml
AutoBouquetsMaker/providers/sat_0192_hd+7.xml
AutoBouquetsMaker/providers/sat_0192_hd+8.xml
AutoBouquetsMaker/providers/sat_0192_hd+9.xml

This bouquet includes all transponders used by the German FTV service HD+ (http://www.hd-plus.de/) at 19.2°E as well as the standard German FTA channels.
As HD+ does not provide LCNs, a CustomLCN configuration is included to arrange channels in a reasonable order.

Add HD+ (Germany) bouquet

---

AutoBouquetsMaker/custom/README.txt
AutoBouquetsMaker/custom/hd_sat_0192_hd+_CustomLCN.xml
AutoBouquetsMaker/custom/hd_sat_0192_hd+_CustomradioLCN.xml
AutoBouquetsMaker/providers/sat_0192_hd+.xml
AutoBouquetsMaker/providers/sat_0192_hd+10.xml
AutoBouquetsMaker/providers/sat_0192_hd+12.xml
AutoBouquetsMaker/providers/sat_0192_hd+13.xml
AutoBouquetsMaker/providers/sat_0192_hd+14.xml
AutoBouquetsMaker/providers/sat_0192_hd+15.xml
AutoBouquetsMaker/providers/sat_0192_hd+16.xml
AutoBouquetsMaker/providers/sat_0192_hd+17.xml
AutoBouquetsMaker/providers/sat_0192_hd+18.xml
AutoBouquetsMaker/providers/sat_0192_hd+19.xml
AutoBouquetsMaker/providers/sat_0192_hd+2.xml
AutoBouquetsMaker/providers/sat_0192_hd+4.xml
AutoBouquetsMaker/providers/sat_0192_hd+5.xml
AutoBouquetsMaker/providers/sat_0192_hd+6.xml
AutoBouquetsMaker/providers/sat_0192_hd+7.xml
AutoBouquetsMaker/providers/sat_0192_hd+8.xml
AutoBouquetsMaker/providers/sat_0192_hd+9.xml

With these additions the HD+ bouquet includes all unencrypted services present in the Deutsche Sender bouquet (sat_192_de_PSB1). Encrypted Austrian services are excluded as they're in the AustriaSat bouquet.

Add sections and more services to HD+ bouquet

---

AutoBouquetsMaker/providers/cable_ie.xml

Hi Guys, Can we add this rename workaround to the cable_ie.xml provider file for the Eurosport channels.

[CABLE IE] - Add rename workaround for Eurosport 1 & 2 services

---

AutoBouquetsMaker/providers/sat_282_sky_uk.xml

This allows users to add STV 2 to the ITV Regions hack in CustomMix

Add STV 2 to ITV Regions

---

AutoBouquetsMaker/providers/cable_uk_virgin.xml

Bike seems to have stopped broadcasting and maybe the same for Sky UK please check before committing  https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=0ahUKEwjP1Zry_L3WAhUJLcAKHSNGApgQFghZMAc&url=http%3A%2F%2Fwww.cyclingweekly.com%2Fnews%2Flatest-news%2Fbike-channel-confirms-closure-350100&usg=AFQjCNGSyebYo3Ce2xm4R0MmKtthdIi3kA

Add Bike to blacklist

---

AutoBouquetsMaker/custom/README.txt
AutoBouquetsMaker/src/scanner/bouquetswriter.py
AutoBouquetsMaker/src/scanner/tools.py

Adds ability to specify service ref types (ie 4097, 5001, etc) on a case-by-case basis for each stream added via custom mix file
All credit goes to @Huevos
This was discussed in below thread:
https://www.world-of-satellite.com/showthread.php?58583-ABM-with-use-of-IPTV-Streams&p=491606&viewfull=1#post491606

Adds ability to specify serviceref type

---

AutoBouquetsMaker/providers/sat_3300_pt_meo.xml
AutoBouquetsMaker/providers/sat_3300_pt_nos.xml
AutoBouquetsMaker/providers/terrestrial_pt_tdt.xml

First stab at adding Portuguese providers MEO & NOS on Hispasat 30.0W, as well as Portuguese terrestrial television provider file.
No real sections (categories), blacklists, channel ordering/swaps, or service hacks.

Adding PT MEO,NOS (Hispasat 30W), TDT (terrestrial)

---

AutoBouquetsMaker/providers/sat_3300_sk_pantelio.xml

Adding Pantelio package.
Setting FEC to 3/4 as reported on a couple of frequency sites as well as experimentally verified, instead of 5/6 as indicated on pantelio.tv.

Adding Pantelio on 30W

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

BBC Scotland now seems to be Sky 194 and BBC Scotland HD remains on sky 876.
Second attempt and HD swap for new BBC Scotland Sky channel numbers.

BBC Scotland HD Swap (second attempt at this)

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

The name I gave 53595 "The Craft Store HD" does not match the name it got when it was given a real name.
Though as far as I can see, my name actually shows what it is (it seems to be an HD version of "The Craft Store").
But, at least until I'm sure what they're up to, I suggest we remove the name I gave it for now.

[Sky 28.2] Remove name added for 53595 because it has a real name now that is different!

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

Remove names I added for "QVC HD" and "QVC Style HD" while they were testing.
They have now gone live on Sky UK.
I don't know for sure what state "NBC News NOW HD" is in because I don't have a Sky subscription and it's encrypted.
But I suspect that name is now redundant too.

[Sky 28.2] Remove names for testing channels that have gone live on Sky UK.

---

AutoBouquetsMaker/providers/terrestrial_pt_tdt.xml

As most countries terrestrial is by location instead of by channel, I update the Portuguese TDT to be by location too.
I share my "one-liner" command to retrieve from official TDT site new updates:
```
wget -q -O- 'https://servicos.apps.meo.pt/Services/TDTService.svc/emissores' | python3 -c "import sys, json, unicodedata, re; a=json.load(sys.stdin); b={}
for c in a: d=c['Frequencia'].replace(' ','')[:7].split('-'); b[c['EstacaoEmissora']]=str((int(d[0])+int(d[1]))*1000000//2)
print('\nUpdate for the file \"terrestrial_pt_tdt.xml\":'); t='\t\t<configuration key=\"{}\" frequency=\"{}\">{}</configuration>'
for c,d in sorted(b.items()): print(t.format(re.sub(r'[^a-z0-9]+','_',unicodedata.normalize('NFD',c.lower()).encode('ascii','ignore').decode('utf-8')),d,c))
print('\nUpdate for the file …
```

[Terrestrial] Update Portuguese TDT by location

---

AutoBouquetsMaker/providers/sat_3300_pt_meo.xml
AutoBouquetsMaker/providers/sat_3300_pt_nos.xml

Instead of excluding adult channel, use parental control to block adult channels.

Don't exclude NOS and MEO adult channel, use parental control

---

AutoBouquetsMaker/providers/terrestrial_pt_tdt.xml

So that TDT by channel number be differentiate from channel by location, and at the same time be sorted at the end of the list because is deprecated.

So that TDT by channel number be differentiate and sorted at the end

---

AutoBouquetsMaker/providers/terrestrial_pt_tdt.xml

- Fix terrestrial TDT transponder with wrong NIT center_frequency=754000.000 kHz when it should be 594000.000 kHz.
- Sort dvbtconfigs by key

Fix terrestrial TDT transponder with wrong NIT center_frequency

---

AutoBouquetsMaker/src/scanner/dvbscanner.py
AutoBouquetsMaker/src/scanner/manager.py

Fix DVB-T frequency when 1 transponder found at the NIT table and that frequency is different from tune frequency.
Let me try to explain this code: 
- apply only to DVB-T;
- it will run when the read of NIT only found one frequency, thus transponder count == 1;
- will not run when the read of NIT found multiple frequencies;
- when the NIT found frequency is missing or different from the tuned frequency, it is obvious a error, because it would be stupid to have 1 frequency to read the NIT and a different frequency for the services;

Fix DVB-T frequency when 1 transponder found at the NIT table and that frequency is different from tune frequency.

---

AutoBouquetsMaker/providers/sat_282_sky_irl.xml
AutoBouquetsMaker/providers/sat_282_sky_uk.xml

Fix HD swaps after Sky renumbered channels in the News section.

[Sky 28.2] HD swap fix after News section renumber

---

.github/workflows/autobouquetsmaker.yml

python -m compileall -l flag was included by mistake from copying AutoBouquets workflow, doh!

allow workflow to recurse into subdirectories

---

AutoBouquetsMaker/lib/dvbreader.c
AutoBouquetsMaker/providers/sat_192_movistar_plus_esp.xml
AutoBouquetsMaker/src/scanner/dvbscanner.py

- Changes to dvbreader to parse required region 0x82.
- Support to process multiple regions for a single provider (required for Movistar+). This is achieved with a new special descriptor_tag 0xFF. Duplicates are managed by defining a processing priority per region. For Movistar, 0x83 takes priority over 0x82.
- Updates to provider file.
This pull request overrides #277 and fixes missing channels reported here: https://github.com/oe-alliance/AutoBouquetsMaker/issues/276#issuecomment-1724630961

Movistar+ 19.2 missing channels
